require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "tmp/**/*"

  ExtraDetails: true

  NewCops: enable

  TargetRubyVersion: 3.0

#################### Layout ###########################

Layout/ExtraSpacing:
  AllowBeforeTrailingComments: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/LineLength:
  Exclude:
    - "db/migrate/*.rb"
    - "db/schema.rb"
    - "config/initializers/devise.rb"
    - "app/views/admin/**/*.arb"

#################### Metrics ###############################

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - "app/admin/**/*.rb"
    - "config/environments/*.rb"
    - "config/initializers/*.rb"
    - "db/**/*.rb"
    - "app/views/admin/**/*.arb"

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/**/*.rb"

#################### Style ###############################

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - "db/**/*.rb"
    - "Gemfile"
    - "Rakefile"
    - "config/**/*.rb"
    - "config.ru"

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
